FROM ghcr.io/key4hep/key4hep-externals-ubuntu24:latest

# Create the environment setup script
RUN . /opt/setup_spack.sh && \
    echo ". /opt/setup_spack.sh" > ${HOME}/setup_env.sh && \
    echo "cd ${SPACK_ROOT}/var/key4hep-spack/environments/key4hep-sim-reco" >> ${HOME}/setup_env.sh && \
    echo "spack env activate ." >> ${HOME}/setup_env.sh && \
    echo "spack env status" >> ${HOME}/setup_env.sh

# Concretize the stack
RUN . ${HOME}/setup_env.sh && \
    spack concretize --reuse

# Installing fragments of dependency tree in separate layers for cached debugging
ENV SPACK_INSTALL_OPTS="--only-concrete --no-add --fail-fast"

RUN . ${HOME}/setup_env.sh && \
    spack spec -NIt && \
    spack install ${SPACK_INSTALL_OPTS} && \
    spack clean -a
