###############################################################################
#  Repository: ${REPOSITORY}/key4hep-externals
#  Tag:        ${VERSION}-ubuntu24
###############################################################################

FROM ghcr.io/key4hep/key4hep-images/ubuntu24:latest

# Picking specific commits
ARG SPACK_COMMIT=6cb16c39ab85fbc211e50be804fa7a15f24ccebc
ARG COMMIT_SHA=e49a0639ff987a84fa0c6263e068776f9d7b6f67
ARG GITHUB_REPOSITORY=key4hep/key4hep-spack

# Setting up Spack
RUN git clone https://github.com/spack/spack.git /opt/spack && \
    echo ". /opt/spack/share/spack/setup-env.sh" >> /opt/setup_spack.sh && \
    echo "alias setup_spack=\". /opt/setup_spack.sh\"" >> /etc/profile.d/aliases.sh

# Using specific commit of Key4hep repository if requested
RUN if [ -n "${SPACK_COMMIT}" ]; then \
      cd /opt/spack; \
      git checkout ${SPACK_COMMIT}; \
    fi

# Configure spack environment with:
# - System compilers
# - Buildcache
ENV SPACK_COLOR="always"
ARG SPACK_BUILDCACHE
ARG OCI_USERNAME
RUN --mount=type=secret,id=ocipass \
    OCI_PASSWORD=$(cat /run/secrets/ocipass) && \
    . /opt/setup_spack.sh && \
    spack config add 'config:install_tree:padded_length:128' && \
    spack compiler find && \
    if [ -n "${SPACK_BUILDCACHE}" ]; then \
        spack mirror add --oci-username "${OCI_USERNAME}" --oci-password "${OCI_PASSWORD}" --unsigned --autopush local-buildcache "${SPACK_BUILDCACHE}";\
    fi

RUN . /opt/setup_spack.sh && \
    REPOPATH=${SPACK_ROOT}/var/key4hep-spack && \
    git clone https://github.com/${GITHUB_REPOSITORY} ${REPOPATH} && \
    cd ${REPOPATH} && \
    git checkout ${COMMIT_SHA} && \
    cd -

# Apply our patches to spack
RUN . /opt/setup_spack.sh && \
    REPOPATH=${SPACK_ROOT}/var/key4hep-spack && \
    cd /opt/spack && \
    . ${REPOPATH}/.cherry-pick && \
    cd -

# Add the package repositories
RUN . /opt/setup_spack.sh && \
    spack repo add --scope system ${SPACK_ROOT}/var/key4hep-spack

# Create the release environment
RUN . /opt/setup_spack.sh && \
    cd ${SPACK_ROOT}/var/key4hep-spack/environments/key4hep-dev-external && \
    spack env activate . && \
    cd - && \
    echo ". /opt/setup_spack.sh" > ${HOME}/setup_env.sh && \
    echo "cd ${SPACK_ROOT}/var/key4hep-spack/environments/key4hep-dev-external" >> ${HOME}/setup_env.sh && \
    echo "spack env activate ." >> ${HOME}/setup_env.sh && \
    echo "cd -" >> ${HOME}/setup_env.sh && \
    echo "spack env status" >> ${HOME}/setup_env.sh

# Concretizing the stack reusing system packages as external
RUN . ${HOME}/setup_env.sh && \
    spack concretize --reuse

# Installing fragments of dependency tree in separate layers for cached debugging
ENV SPACK_INSTALL_OPTS="--only-concrete --no-add --fail-fast"

RUN . ${HOME}/setup_env.sh && \
    spack spec -NIt && \
    spack install ${SPACK_INSTALL_OPTS} && \
    spack mirror remove local-buildcache && \
    spack clean -a
