FROM ghcr.io/key4hep/key4hep-externals-ubuntu24:reco-image

# Install rust (TODO: Pull to externals image?)
RUN curl https://sh.rustup.rs -sSf | bash -s -- -y && \
    echo ". $HOME/.cargo/env" > ${HOME}/setup_env.sh

# Install llvm
RUN apt-get update && \
    apt-get install -y lsb-release wget software-properties-common gnupg && \
    bash -c "$(wget -O - https://apt.llvm.org/llvm.sh)" && \
    update-alternatives --install /usr/bin/clang clang /usr/bin/clang-20 200 && \
    update-alternatives --install /usr/bin/clang++ clang++ /usr/bin/clang++-20 200

# Make sure we pull in the current version of the branch
RUN . /opt/setup_spack.sh && \
    cd ${SPACK_ROOT}/var/key4hep-spack && \
    git fetch && \
    git checkout origin/lcws-tutorial

# Configure spack environment with:
# - System compilers
# - Buildcache
ENV SPACK_COLOR="always"
ARG SPACK_BUILDCACHE
ARG OCI_USERNAME
RUN . /opt/setup_spack.sh && \
    spack config add 'config:install_tree:padded_length:128' && \
    spack compiler find && \
    if [ -n "${SPACK_BUILDCACHE}" ]; then \
        spack mirror remove local-buildcache || true; \
        spack mirror add --oci-username "${OCI_USERNAME}" --oci-password-variable OCI_PASSWORD --unsigned --autopush local-buildcache "${SPACK_BUILDCACHE}";\
    fi

# Create the environment setup script
RUN . /opt/setup_spack.sh && \
    echo ". /opt/setup_spack.sh" >> ${HOME}/setup_env.sh && \
    echo "cd ${SPACK_ROOT}/var/key4hep-spack/environments/key4hep-sim-reco" >> ${HOME}/setup_env.sh && \
    echo "spack env activate ." >> ${HOME}/setup_env.sh && \
    echo "spack env status" >> ${HOME}/setup_env.sh && \
    cat ${HOME}/setup_env.sh && \
    echo SPACK_ROOT=${SPACK_ROOT}

# Concretize the stack
RUN --mount=type=secret,id=ocipass \
    . ${HOME}/setup_env.sh && \
    spack external find --not-buildable rust llvm && \
    OCI_PASSWORD=$(cat /run/secrets/ocipass) spack concretize -f --reuse

# Installing fragments of dependency tree in separate layers for cached debugging
ENV SPACK_INSTALL_OPTS="--only-concrete --no-add --fail-fast"

RUN --mount=type=secret,id=ocipass \
    . ${HOME}/setup_env.sh && \
    OCI_PASSWORD=$(cat /run/secrets/ocipass) spack spec -NIt && \
    OCI_PASSWORD=$(cat /run/secrets/ocipass) spack install ${SPACK_INSTALL_OPTS} && \
    spack env deactivate && \
    spack clean -a && \
    spack mirror rm local-buildcache
