name: Build with spack cache
description: |
  Build a key4hep-dev-external stack with spack cache.
  This workflow is triggered by the key4hep-spack repository.
  It builds the stack and pushes the build cache to the registry.

on:
  workflow_call:
    inputs:
      target:
        required: true
        type: string

env:
  REGISTRY: ghcr.io

permissions:
  contents: read
  packages: write
  id-token: write
  attestations: write

jobs:
  build:
    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}
      cancel-in-progress: true
    runs-on: ubuntu-latest
    container: ghcr.io/key4hep/key4hep-images/alma9:latest
    steps:
      - name: Setup System Dependencies
        run: |
          dnf update -y
          dnf install -y gcc gcc-c++ gcc-gfortran lbzip2 unzip
          dnf clean all
      - name: Checkout key4hep repository
        uses: actions/checkout@v4
        with:
          repository: key4hep/key4hep-spack
          ref: ${{ github.sha }}
          path: key4hep-spack
      - name: Determine spack and key4hep ref
        id: getref
        run: |
          echo "spack_ref=$(cat key4hep-spack/.latest-commit)" >>${GITHUB_OUTPUT}
      - name: Set up Spack
        uses: spack/setup-spack@v2
        with:
          ref: ${{ steps.getref.outputs.spack_ref }} # Spack version (examples: develop, releases/v0.23)
          color: true                                # Force color output (SPACK_COLOR=always)
          path: spack                           # Where to clone Spack
          buildcache: false                          # No central build cache (incompatible)
      - name: Spack Setup Build Cache
        shell: spack-bash {0}
        run: |
          git -C spack fetch # Needed to fetch the full history for backporting patches
          spack config add 'config:install_tree:padded_length:128'
          spack mirror add --oci-username '${{ github.actor }}' --oci-password '${{ secrets.GITHUB_TOKEN }}' --unsigned --autopush local-buildcache 'oci://ghcr.io/${{ github.repository_owner }}/spack-buildcache'
      - name: Apply the patches
        shell: spack-bash {0}
        run: |
          SPACK_ROOT=$(realpath spack) key4hep-spack/AlmaLinux9/apply_patches.sh key4hep-spack
      - name: Spack Local Setup
        shell: spack-bash {0}
        run: |
          spack --version
          spack repo add key4hep-spack
          spack compiler find
      # The key4hep-dev-external needs to be built first. Otherwise gdb will fail with
      # the following error. Probably some compile-time check being triggered due to a
      # dependency being compiled in the wrong order.
      #
      #     error: expected identifier before numeric constant
      #        180 | # define TRAP_HWBKPT 4
      #            |                      ^
      #
      - name: Spack Build key4hep-dev-external
        shell: spack-bash {0}
        run: |
          spack env activate key4hep-spack/environments/key4hep-dev-external
          spack concretize --reuse
          spack install --only-concrete --no-add --fail-fast
          spack clean -a