name: Build with spack cache
description: |
  Build a key4hep-dev-external stack with spack cache.
  This workflow is triggered by the key4hep-spack repository.
  It builds the stack and pushes the binaries to the cache.

on:
  workflow_call:
    inputs:
      target:
        required: true
        type: string

permissions:
  contents: read
  packages: write
  id-token: write
  attestations: write

jobs:
  build:
    runs-on: ubuntu-latest
    container: ghcr.io/key4hep/key4hep-images/alma9:latest
    steps:
      - name: Setup System Dependencies
        run: |
          dnf update -y
          dnf install -y gcc gcc-c++ gcc-gfortran lbzip2 unzip
          dnf clean all
      - name: Checkout key4hep repository
        uses: actions/checkout@v4
        with:
          repository: key4hep/key4hep-spack
          ref: ${{ github.sha }}
          path: key4hep-spack
      - name: Determine spack ref
        id: getref
        run: |
          echo "spack_ref=$(cat key4hep-spack/.latest-commit)" >>${GITHUB_OUTPUT}
      - name: Set up Spack
        uses: spack/setup-spack@v2
        with:
          ref: ${{ steps.getref.outputs.spack_ref }} # Spack version (examples: develop, releases/v0.23)
          color: true                                # Force color output (SPACK_COLOR=always)
          path: spack                                # Where to clone Spack
          buildcache: false                          # No central build cache (incompatible)
      - name: Spack Setup Build Cache
        shell: spack-bash {0}
        run: |
          git -C spack fetch # Needed to fetch the full history for backporting patches
          spack config add 'config:install_tree:padded_length:128'
          spack mirror add --oci-username '${{ github.actor }}' --oci-password-variable '${{ secrets.GITHUB_TOKEN }}' --unsigned --autopush local-buildcache 'oci://ghcr.io/${{ github.repository_owner }}/spack-buildcache'
      - name: Apply Patches
        shell: spack-bash {0}
        run: |
          cd spack 
          source ../key4hep-spack/.cherry-pick
          cd ..
      - name: Spack Local Setup
        shell: spack-bash {0}
        run: |
          spack --version
          spack repo add key4hep-spack
          spack compiler find
      - name: Spack Build key4hep-dev-external
        shell: spack-bash {0}
        run: |
          spack env activate key4hep-spack/environments/key4hep-dev-external
          spack concretize --reuse
          spack install --only-concrete --no-add --fail-fast
          spack clean -a