name: Concretize
description: |
  This workflow concretizes the spack environment that was used for the last nightly or release build

on:
  push:
    branches:
    - main
  pull_request:
  workflow_dispatch:

jobs:
  concretize:
    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}-${{ matrix.image }}-${{ matrix.build_type }}
      cancel-in-progress: true
    strategy:
      matrix:
        image: [alma9, ubuntu24]
        build_type: [release, nightly]
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/key4hep/key4hep-images/${{ matrix.image }}-cvmfs
      options: --privileged
    defaults:
      run:
        shell: bash
    steps:
      - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 #v7
      - name: Set up cvmfs
        run: /mount.sh
      - name: Setup environment and concretize
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          KEY4HEP_SPACK_ROOT: ${{ github.workspace }}
        run: |
            cd /
            git clone https://github.com/spack/spack -q
            cd spack
            git checkout $(cat ${KEY4HEP_SPACK_ROOT}/.latest-commit)
            cd ..
            source spack/share/spack/setup-env.sh
            git clone https://github.com/spack/spack-packages -q
            cd spack-packages
            git checkout $(cat ${KEY4HEP_SPACK_ROOT}/.latest-packages-commit)
            cd ..

            spack repo set --destination /spack-packages builtin
            spack repo add ${KEY4HEP_SPACK_ROOT}

            cd spack-packages
            source ${KEY4HEP_SPACK_ROOT}/.cherry-pick
            cd ..

            if [ "${{ matrix.build_type }}" = "release" ]; then
                env=key4hep-release-opt
            elif [ "${{ matrix.build_type }}" = "nightly" ]; then
                env=key4hep-nightly-opt
                python3 ${KEY4HEP_SPACK_ROOT}/scripts/fetch_nightly_versions.py --path ${KEY4HEP_SPACK_ROOT}/environments/key4hep-common/packages.yaml --extra-path ${KEY4HEP_SPACK_ROOT}/environments/key4hep-common-opt/packages.yaml --skip-connection-errors ""
            else
                echo "Unknown build type"
                exit 1
            fi
            cd ${KEY4HEP_SPACK_ROOT}/environments/${env}

            echo "========="
            echo "spack.yaml"
            cat spack.yaml
            echo "========="
            echo "packages.yaml"
            cat packages.yaml
            echo "========="
            echo "key4hep-common/packages.yaml"
            cat ${KEY4HEP_SPACK_ROOT}/environments/key4hep-common/packages.yaml
            echo "========="

            spack env activate .
            spack concretize
