name: Concretize nightly with latest spack
description: |
  Concretize the nightlies using the last commit of the develop branch of spack
  instead of picking up the pinned version from .latest-commit.
  spack-packages still uses the pinned version from .latest-packages-commit
  with the usual cherry-picks applied. This allows early detection of breaking
  changes in upstream spack.

on:
  push:
    branches:
    - main
  pull_request:
  workflow_dispatch:

jobs:
  concretize-nightly-latest-spack:
    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}-${{ matrix.image }}
      cancel-in-progress: true
    strategy:
      matrix:
        image: [alma9, ubuntu24]
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/key4hep/key4hep-images/${{ matrix.image }}-cvmfs
      options: --privileged
    defaults:
      run:
        shell: bash
    steps:
      - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 #v7
      - name: Set up cvmfs
        run: /mount.sh
      - name: Setup environment and concretize
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          KEY4HEP_SPACK_ROOT: ${{ github.workspace }}
        run: |
            cd /
            git clone https://github.com/spack/spack -q
            cd spack
            echo "Spack checked out at: $(git rev-parse HEAD)"
            cd ..
            source spack/share/spack/setup-env.sh
            git clone https://github.com/spack/spack-packages -q
            cd spack-packages
            git checkout $(cat ${KEY4HEP_SPACK_ROOT}/.latest-packages-commit)
            cd ..

            spack repo set --destination /spack-packages builtin
            spack repo add ${KEY4HEP_SPACK_ROOT}

            cd spack-packages
            source ${KEY4HEP_SPACK_ROOT}/.cherry-pick
            cd ..

            python3 ${KEY4HEP_SPACK_ROOT}/scripts/fetch_nightly_versions.py --path ${KEY4HEP_SPACK_ROOT}/environments/key4hep-common/packages.yaml --extra-path ${KEY4HEP_SPACK_ROOT}/environments/key4hep-common-opt/packages.yaml --skip-connection-errors ""

            cd ${KEY4HEP_SPACK_ROOT}/environments/key4hep-nightly-opt

            echo "========="
            echo "spack.yaml"
            cat spack.yaml
            echo "========="
            echo "packages.yaml"
            cat packages.yaml
            echo "========="
            echo "key4hep-common/packages.yaml"
            cat ${KEY4HEP_SPACK_ROOT}/environments/key4hep-common/packages.yaml
            echo "========="

            spack env activate .
            spack concretize
