name: Test Setup Scripts

on:
  push:
    paths:
      - scripts/cvmfs/setup-nightlies.sh
      - scripts/cvmfs/setup-releases.sh
  pull_request:
    paths:
      - scripts/cvmfs/setup-nightlies.sh
      - scripts/cvmfs/setup-releases.sh
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  test-nightlies:
    strategy:
      fail-fast: false
      matrix:
        include:
          - os: alma9
            image: ghcr.io/key4hep/key4hep-images/alma9-cvmfs
          - os: ubuntu24
            image: ghcr.io/key4hep/key4hep-images/ubuntu24-cvmfs
          - os: ubuntu26
            image: ghcr.io/key4hep/key4hep-images/ubuntu26-cvmfs
    runs-on: ubuntu-latest
    container:
      image: ${{ matrix.image }}
      options: --privileged
    steps:
      - name: Set up cvmfs
        run: /mount.sh

      - uses: actions/checkout@v4

      - name: Source nightlies setup script (opt)
        run: bash -c 'source ${{ github.workspace }}/scripts/cvmfs/setup-nightlies.sh'

      - name: Source nightlies setup script (dbg)
        run: bash -c 'source ${{ github.workspace }}/scripts/cvmfs/setup-nightlies.sh -d'

  test-releases:
    strategy:
      fail-fast: false
      matrix:
        include:
          - os: alma9
            image: ghcr.io/key4hep/key4hep-images/alma9-cvmfs
          - os: ubuntu24
            image: ghcr.io/key4hep/key4hep-images/ubuntu24-cvmfs
    runs-on: ubuntu-latest
    container:
      image: ${{ matrix.image }}
      options: --privileged
    steps:
      - name: Set up cvmfs
        run: /mount.sh

      - uses: actions/checkout@v4

      - name: Source releases setup script (opt)
        run: bash -c 'source ${{ github.workspace }}/scripts/cvmfs/setup-releases.sh'

      - name: Source releases setup script (dbg)
        run: bash -c 'source ${{ github.workspace }}/scripts/cvmfs/setup-releases.sh -d'
