name: Test Setup Scripts

on:
  push:
    branches:
      - main
    paths:
      - scripts/cvmfs/setup-nightlies.sh
      - scripts/cvmfs/setup-releases.sh
  pull_request:
    paths:
      - scripts/cvmfs/setup-nightlies.sh
      - scripts/cvmfs/setup-releases.sh
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  test-nightlies:
    strategy:
      fail-fast: false
      matrix:
        include:
          - os: alma9
            image: ghcr.io/key4hep/key4hep-images/alma9-cvmfs
          - os: ubuntu24
            image: ghcr.io/key4hep/key4hep-images/ubuntu24-cvmfs
          - os: ubuntu26
            image: ghcr.io/key4hep/key4hep-images/ubuntu26-cvmfs
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Start container
        run: |
          docker run --name container --privileged \
            -v ${GITHUB_WORKSPACE}:/key4hep-spack \
            -d ${{ matrix.image }} tail -f /dev/null

      - name: Source nightlies setup script (opt)
        run: |
          docker exec container bash -c "/mount.sh && source /key4hep-spack/scripts/cvmfs/setup-nightlies.sh"

      - name: Source nightlies setup script (dbg)
        run: |
          docker exec container bash -c "/mount.sh && source /key4hep-spack/scripts/cvmfs/setup-nightlies.sh -d"

  test-releases:
    strategy:
      fail-fast: false
      matrix:
        include:
          - os: alma9
            image: ghcr.io/key4hep/key4hep-images/alma9-cvmfs
          - os: ubuntu24
            image: ghcr.io/key4hep/key4hep-images/ubuntu24-cvmfs
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Start container
        run: |
          docker run --name container --privileged \
            -v ${GITHUB_WORKSPACE}:/key4hep-spack \
            -d ${{ matrix.image }} tail -f /dev/null

      - name: Source releases setup script (opt)
        run: |
          docker exec container bash -c "/mount.sh && source /key4hep-spack/scripts/cvmfs/setup-releases.sh"

      - name: Source releases setup script (dbg)
        run: |
          docker exec container bash -c "/mount.sh && source /key4hep-spack/scripts/cvmfs/setup-releases.sh -d"
